name: choco
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:  # https://community.chocolatey.org/packages/fluidsynth
        fluidsynth-version: [ 2.4.3, 2.4.4, 2.4.5 ]
    runs-on: windows-latest
    steps:  # fluidsynth v2.4.3 works but the default v2.4.4 fails.
      - run: choco install fluidsynth --version ${{ matrix.fluidsynth-version }}
      - run: fluidsynth --version
      - shell: python
        run: |
          import ctypes
          import os
          from os import add_dll_directory
          from ctypes import CDLL
          
          def load_libfluidsynth() -> str:
              libs = "fluidsynth libfluidsynth libfluidsynth-3 libfluidsynth-2 libfluidsynth-1"
              for lib_name in libs.split():
                  if lib := ctypes.util.find_library(lib_name):
                      print(f"'{lib_name}' was found as {lib}.")
                      return lib
              raise FileNotFound
  
          os.add_dll_directory('C:\\tools\\fluidsynth\\bin')
          lib = load_libfluidsynth()
          print(f"{CDLL(lib) = }")
